=== kennykarnama/ilfx/xsd/KPMRRiskProfile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:kpmr="http://example.com/kpmr"
        targetNamespace="http://example.com/kpmr"
        elementFormDefault="qualified">
  
  <!-- Root Element -->
  <xs:element name="kpmr_risk_profile_tree">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="node" type="kpmr:NodeType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Node Type (recursive structure) -->
  <xs:complexType name="NodeType">
    <xs:sequence>
      <xs:element name="risiko_name" type="xs:string"/>
      <xs:element name="profile_id" type="xs:string"/>
      <xs:element name="assessment_factor" type="xs:string"/>
      <xs:element name="derived_from" type="xs:string"/>
      <xs:element name="threshold" type="xs:string"/>
      <xs:element name="input_type" type="xs:string"/>
      <xs:element name="source_reference" type="xs:string"/>
      <xs:element name="calculation_logic" type="xs:string"/>
      <xs:element name="risk_id" type="xs:integer"/>
      <xs:element name="id" type="xs:integer"/>
      <xs:element name="weight" type="xs:decimal" minOccurs="0"/>
      <xs:element name="score_formula" minOccurs="0">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name="rating_rule" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Rules to derive the rating</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name="score_rule" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Rules to derive the score</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name="value_rule" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Rules to derive the value</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name="computed_rating" type="xs:string" minOccurs="0"></xs:element>
      <xs:element name="computed_score" type="xs:string" minOccurs="0"></xs:element>
      <xs:element name="computed_value" type="xs:string" minOccurs="0"></xs:element>
      <xs:element name="computed_weighted_score" type="xs:string" minOccurs="0"></xs:element>

      <xs:element name="children" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="node" type="kpmr:NodeType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== kennykarnama/ilfx/build/riskprokpmr_out.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<kpmr_risk_profile_tree xmlns="http://example.com/kpmr" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.com/kpmr ../xsd/KPMRRiskProfile.xsd">
  <node>
    <risiko_name>Risiko Operasional</risiko_name>
    <profile_id>RK04000000</profile_id>
    <assessment_factor/>
    <derived_from/>
    <threshold/>
    <input_type/>
    <source_reference/>
    <calculation_logic/>
    <risk_id>11</risk_id>
    <id>63</id>
    <weight>0</weight>
    <score_formula/>
    <children>
      <node>
        <risiko_name>Risiko Operasional</risiko_name>
        <profile_id>RK04001000</profile_id>
        <assessment_factor>Tata Kelola (Risk Governance)</assessment_factor>
        <derived_from>Risk Profile</derived_from>
        <threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</threshold>
        <input_type>system</input_type>
        <source_reference/>
        <calculation_logic>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</calculation_logic>
        <risk_id>11</risk_id>
        <id>43</id>
        <weight>0</weight>
        <score_formula/>
        <children>
          <node>
            <risiko_name>Risiko Operasional</risiko_name>
            <profile_id>RK04001001</profile_id>
            <assessment_factor>Penetapan tingkat Risiko operasional yang akan diambil oleh LJK dan toleransi Risikonya sejalan dengan sasaran strategis dan strategi bisnis LJK secara keseluruhan</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold/>
            <input_type>system</input_type>
            <source_reference>SK04001001</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>11</risk_id>
            <id>44</id>
            <weight>0</weight>
            <score_formula/>
          </node>
          <node>
            <risiko_name>Risiko Operasional</risiko_name>
            <profile_id>RK04001002</profile_id>
            <assessment_factor>Awareness dan pemahaman Dewan Komisaris dan Direksi LJK mengenai manajemen Risiko operasional</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold/>
            <input_type>system</input_type>
            <source_reference>SK04001002</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>11</risk_id>
            <id>45</id>
            <weight>0</weight>
            <score_formula/>
          </node>
          <node>
            <risiko_name>Risiko Operasional</risiko_name>
            <profile_id>RK04001003</profile_id>
            <assessment_factor>Budaya Risiko operasional dan internalisasi budaya Risiko pada seluruh LJK dalam Konglomerasi Keuangan</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold/>
            <input_type>system</input_type>
            <source_reference>SK04001003</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>11</risk_id>
            <id>46</id>
            <weight>0</weight>
            <score_formula/>
          </node>
          <node>
            <risiko_name>Risiko Operasional</risiko_name>
            <profile_id>RK04001004</profile_id>
            <assessment_factor>Pelaksanaan tugas Dewan Komisaris dan Direksi LJK secara keseluruhan untuk Risiko operasional</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold/>
            <input_type>system</input_type>
            <source_reference>SK04001004</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>11</risk_id>
            <id>47</id>
            <weight>0</weight>
            <score_formula/>
          </node>
        </children>
      </node>
      <node>
        <risiko_name>Risiko Operasional</risiko_name>
        <profile_id>RK04003000</profile_id>
        <assessment_factor>Proses Manajemen Risiko, SIM dan SDM</assessment_factor>
        <derived_from>Risk Profile</derived_from>
        <threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</threshold>
        <input_type>system</input_type>
        <source_reference/>
        <calculation_logic>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</calculation_logic>
        <risk_id>11</risk_id>
        <id>52</id>
        <weight>0</weight>
        <score_formula/>
        <children>
          <node>
            <risiko_name>Risiko Operasional</risiko_name>
            <profile_id>RK04003001</profile_id>
            <assessment_factor>Proses manajemen Risiko operasional oleh LJK dalam Konglomerasi Keuangan dalam mengidentifikasi, mengukur, memantau, dan mengendalikan Risiko operasional</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold/>
            <input_type>system</input_type>
            <source_reference>SK04003001</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>11</risk_id>
            <id>53</id>
            <weight>0</weight>
            <score_formula/>
          </node>
          <node>
            <risiko_name>Risiko Operasional</risiko_name>
            <profile_id>RK04003002</profile_id>
            <assessment_factor>Keandalan Business Continuity Management Konglomerasi Keuangan.</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold/>
            <input_type>system</input_type>
            <source_reference>SK04003002</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>11</risk_id>
            <id>54</id>
            <weight>0</weight>
            <score_formula/>
          </node>
          <node>
            <risiko_name>Risiko Operasional</risiko_name>
            <profile_id>RK04003003</profile_id>
            <assessment_factor>Terdapat Sistem Informasi Manajemen Terintegrasi (SIMT) untuk Risiko operasional sehingga menghasilkan pelaporan Risiko operasional secara keseluruhan yang komprehensif dan terintegrasi</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold/>
            <input_type>system</input_type>
            <source_reference>SK04003003</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>11</risk_id>
            <id>55</id>
            <weight>0</weight>
            <score_formula/>
          </node>
          <node>
            <risiko_name>Risiko Operasional</risiko_name>
            <profile_id>RK04003004</profile_id>
            <assessment_factor>Pemenuhan sumber daya manusia pada LJK dalam Konglomerasi Keuangan baik dari sisi kuantitas maupun kompetensi pada fungsi manajemen Risiko operasional</assessment_factor>
            <derived_from>data source</derived_from>
            <threshold/>
            <input_type>system</input_type>
            <source_reference>SK04003004</source_reference>
            <calculation_logic>Rating : derived dari hasil penginputan Rating Consolidated KPMR
Score: derived dari Rating to check score parameter
IF(I7=1,92,IF(I7=2,76,IF(I7=3,60,IF(I7=4,44,IF(I7=5,28)))))

Bobot : from Parameter
SxB : Score * Bobot</calculation_logic>
            <risk_id>11</risk_id>
            <id>56</id>
            <weight>0</weight>
            <score_formula/>
          </node>
        </children>
      </node>
      <node>
        <risiko_name>Risiko Operasional</risiko_name>
        <profile_id>RK04004000</profile_id>
        <assessment_factor>Sistem Pengendalian</assessment_factor>
        <derived_from>Risk Profile</derived_from>
        <threshold>5 : Score&lt;=36,
4:  36 &lt; Score &lt;=52
3:  52 &lt; Score &lt;=68
2:  68 &lt; Score &lt;=84
1:  84 &lt; Score &lt;=100</threshold>
        <input_type>system</input_type>
        <source_reference/>
        <calculation_logic>Score : Sum dari SxB per section
Bobot: from parameter
SxB : Score * Bobot
Rating : derived dari Score vs Threshold
</calculation_logic>
        <risk_id>11</risk_id>
        <id>57</id>
        <weight>0</weight>
        <score_formula/>
        <children>
